# Generated by Django 5.2.16 on 2026-08-03 05:02

import django.core.validators
import django.db.models.deletion
import question_bank.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subject', models.CharField(choices=[('calculus', '高等数学'), ('final_linear_algebra', '决赛·线性代数')], max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='question_bank.knowledgepoint')),
            ],
            options={
                'ordering': ['subject', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)])),
                ('stage', models.CharField(choices=[('preliminary', '初赛'), ('final', '决赛')], max_length=20)),
                ('scope_category', models.CharField(default='non_math_a', editable=False, max_length=20)),
                ('original_category_label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('exam_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, upload_to=question_bank.models.paper_pdf_path, validators=[question_bank.models.validate_pdf])),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('reviewed', '已复核'), ('published', '已发布')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-edition', '-stage'],
                'constraints': [models.CheckConstraint(condition=models.Q(('edition__gte', 1), ('edition__lte', 17)), name='paper_edition_1_to_17'), models.CheckConstraint(condition=models.Q(('scope_category', 'non_math_a')), name='paper_scope_non_math_a'), models.CheckConstraint(condition=models.Q(('stage__in', ['preliminary', 'final'])), name='paper_stage_preliminary_or_final'), models.UniqueConstraint(fields=('edition', 'stage'), name='unique_paper_edition_stage')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('question_type', models.CharField(choices=[('fill_blank', '填空题'), ('calculation', '计算题'), ('proof', '证明题'), ('comprehensive', '综合题')], max_length=30)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stem_md', models.TextField()),
                ('answer_md', models.TextField(blank=True)),
                ('solution_md', models.TextField()),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('source_page', models.PositiveSmallIntegerField()),
                ('source_crop', models.CharField(blank=True, max_length=500)),
                ('text_checked', models.BooleanField(default=False)),
                ('formula_checked', models.BooleanField(default=False)),
                ('solution_checked', models.BooleanField(default=False)),
                ('unresolved_ocr_items', models.PositiveSmallIntegerField(default=0)),
                ('katex_errors', models.PositiveSmallIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('reviewed', '已复核'), ('published', '已发布')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_bank.paper')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['paper', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionKnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question_bank.knowledgepoint')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='knowledge_points',
            field=models.ManyToManyField(related_name='questions', through='question_bank.QuestionKnowledgePoint', to='question_bank.knowledgepoint'),
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_wrong_by', to='question_bank.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='question_bank.question')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_user_favorite')],
            },
        ),
        migrations.AddConstraint(
            model_name='questionknowledgepoint',
            constraint=models.UniqueConstraint(fields=('question', 'knowledge_point'), name='unique_question_knowledge_point'),
        ),
        migrations.AddConstraint(
            model_name='questionknowledgepoint',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('question',), name='one_primary_knowledge_per_question'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'question_type'], name='question_ba_status_2adc98_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['paper', 'sort_order'], name='question_ba_paper_i_942f9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('paper', 'question_no'), name='unique_question_number_per_paper'),
        ),
        migrations.AddConstraint(
            model_name='wrongquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_wrong_question'),
        ),
    ]
