# Generated by Django 5.2.17 on 2026-08-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paper',
            name='paper_stage_preliminary_or_final',
        ),
        migrations.AlterField(
            model_name='paper',
            name='stage',
            field=models.CharField(choices=[('preliminary', '初赛'), ('preliminary_b', '初赛（B类）'), ('final', '决赛')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['preliminary', 'preliminary_b', 'final'])), name='paper_stage_preliminary_or_final'),
        ),
    ]
