# Generated by Django 5.2.17 on 2026-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_remove_paper_paper_stage_preliminary_or_final_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paper',
            name='paper_stage_preliminary_or_final',
        ),
        migrations.AlterField(
            model_name='paper',
            name='stage',
            field=models.CharField(choices=[('preliminary', '初赛'), ('preliminary_b', '初赛（B类）'), ('final_b', '决赛（B类）'), ('final', '决赛')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['preliminary', 'preliminary_b', 'final', 'final_b'])), name='paper_stage_preliminary_or_final'),
        ),
    ]
